- name: install remi repository
  command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
- name: install apache
  yum: name=httpd state=latest
- name: start apache and enabled
  service: name=httpd state=started enabled=yes
- name: change owner
  file: dest=/var/www/html owner=vagrant recurse=yes
