- name: Postgres Download
  yum: name=http://yum.pgrpms.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present
- name: copy CentOS-Base.repo.custom
  copy: src=CentOS-Base.repo.custom dest=/etc/yum.repos.d/CentOS-Base.repo backup=yes
- name: install Postgres
  yum: name={{item}} state=present
  with_items:
    - postgresql-server
    - postgresql94-contrib
    - php-pgsql
    - policycoreutils-python
    - python-psycopg2
- name: postgresql initdb
  shell: service postgresql-9.4 initdb
         creates=/var/lib/pgsql/9.4/data/postgresql.conf
- name: start postgresql
  service: name=postgresql-9.4 state=started  enabled=yes
- name: postgres user sudores
  lineinfile:
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: 0440
    line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"
- name : create database
  postgresql_db:
    name: "{{ dbname }}"
    login_user: postgres
    template: template0
    encoding: "UTF-8"
  sudo_user: postgres
  sudo: yes
- name: create user
  postgresql_user:
    db: "{{ dbname }}"
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: ALL
    state: present
    login_user: postgres
  sudo_user: postgres
  sudo: yes
